env: LOCAL

http:
  writeTimeout: 15
  readTimeout: 15

log:
  dir:
  file: lynx.log
  level: DEBUG

lynx-database:
  host: localhost
  port: 5432
  user: root
  password: root
  database: lynx
  maxIdle: 5
  maxOpen: 10

app-config:
  short-link-len: 5
  default-url: https://nxtrade-dev-api.iouring.in/webapp
  domain: https://nxtrade-dev-api.iouring.in
  android:
    has-app: true #boolean
    android-url: https://nxtrade-dev-api.iouring.in/android #if there is no app this will work
    app-uri-scheme: https://nxtrade-dev-tj-links.iouring.in
    behavior: playsearch #playsearch or custom navigation if app is not installed
    google-play-search-url: https://play.google.com/store/apps/details?id=com.nxtrad.cubeplus
    custom-url:
      fallback-url: https://google.com #if uri scheme failed
      package-name: com.iouring.tradejini.dev
    app-links:
      enable: true #boolean
      certificate: #can be multiple
        -
  ios:
    has-app: true #boolean
    ios-url: https://nxtrade-dev-api.iouring.in/ios #if there is no app this will work
    app-uri-scheme: https://nxtrade-dev-tj-links.iouring.in
    behavior: #playsearch or custom
    app-store-search-url: https://apps.apple.com/in/app/cubeplus-by-tradejini/id6445836933
    custom-url:
      fallback-url: https://google.com
      app-id: id6445836933
    universal-links:
      enable: true #boolean
      bundle-identifier: com.iouring.tradejini.dev.ios
      app-prefix:

  social-media:
    title: testing
    description: testing description
    thumbnail-image: https://img.fkcdn.com/image/xif0q/shoe/v/p/a/-original-imagqe2yhkpexhvz.jpeg
  desktop:
    default-url: https://nxtrade-dev-api.iouring.in/webapp
    windows-url: https://nxtrade-dev-api.iouring.in/webapp-windows
    mac-url: https://nxtrade-dev-api.iouring.in/mac-url
