package main

const (
	INSERT_SHORT_LINK = `INSERT INTO LINKS (SHORT_CODE,DATA,WEB_URL,ANDROID,IOS,SOCIAL,EXPIRY) 
		VALUES ($1,$2,$3,$4,$5,$6,$7)`
	GET_LINK_DATA = `SELECT DATA,WEB_URL,ANDROID,IOS,SOCIAL,EXPIRY FROM LINKS WHERE SHORT_CODE = $1`
)
